"""Add inventory table

Revision ID: 16cd011c12ef
Revises: 820e73ced5e3
Create Date: 2025-05-27 06:41:06.496474

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '16cd011c12ef'
down_revision = '820e73ced5e3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('inventory', schema=None) as batch_op:
        batch_op.add_column(sa.Column('stock', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('location', sa.String(length=100), nullable=True))
        batch_op.drop_column('last_updated')
        batch_op.drop_column('stock_available')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('inventory', schema=None) as batch_op:
        batch_op.add_column(sa.Column('stock_available', sa.INTEGER(), nullable=False))
        batch_op.add_column(sa.Column('last_updated', sa.DATETIME(), nullable=True))
        batch_op.drop_column('location')
        batch_op.drop_column('stock')

    # ### end Alembic commands ###
