"""Recreate production_request table

Revision ID: 289e5b5abbe2
Revises: 126418b90797
Create Date: 2025-05-27 16:45:42.398816

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '289e5b5abbe2'
down_revision = '126418b90797'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('production_request',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('product', sa.String(length=100), nullable=False),
    sa.Column('qty', sa.Integer(), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('requested_by', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['requested_by'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('production_request')
    # ### end Alembic commands ###
