"""Added description column to Request model

Revision ID: 56360541109e
Revises: 87338a7389ba
Create Date: 2025-05-26 11:10:38.496066

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '56360541109e'
down_revision = '87338a7389ba'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('request', schema=None) as batch_op:
        batch_op.add_column(sa.Column('description', sa.Text(), nullable=False))
        batch_op.add_column(sa.Column('sla_breach', sa.Boolean(), nullable=True))
        batch_op.alter_column('request_type',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=100),
               existing_nullable=False)
        batch_op.alter_column('status',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.String(length=50),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('request', schema=None) as batch_op:
        batch_op.alter_column('status',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=20),
               existing_nullable=True)
        batch_op.alter_column('request_type',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=50),
               existing_nullable=False)
        batch_op.drop_column('sla_breach')
        batch_op.drop_column('description')

    # ### end Alembic commands ###
