"""Add product_name, request_category, qty, priority to Request

Revision ID: 820e73ced5e3
Revises: 89e8790ca778
Create Date: 2025-05-26 17:25:03.019461

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '820e73ced5e3'
down_revision = '89e8790ca778'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('request', schema=None) as batch_op:
        batch_op.add_column(sa.Column('product_name', sa.String(length=100), nullable=False))
        batch_op.add_column(sa.Column('request_category', sa.String(length=100), nullable=False))
        batch_op.add_column(sa.Column('qty', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('priority', sa.String(length=20), nullable=True))
        batch_op.alter_column('description',
               existing_type=sa.TEXT(),
               nullable=True)
        batch_op.drop_column('request_type')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('request', schema=None) as batch_op:
        batch_op.add_column(sa.Column('request_type', sa.VARCHAR(length=100), nullable=False))
        batch_op.alter_column('description',
               existing_type=sa.TEXT(),
               nullable=False)
        batch_op.drop_column('priority')
        batch_op.drop_column('qty')
        batch_op.drop_column('request_category')
        batch_op.drop_column('product_name')

    # ### end Alembic commands ###
